### PR TITLE
Add support for bower

### PR DESCRIPTION
**Pull request by mklaber**
[bower](http://bower.io) is so much better than the currently [recommended](https://github.com/forcedotcom/SalesforceCanvasFrameworkSDK#how-to-clone-the-sdk-repository) way to reference the SDK. This PR adds a `bower.json` file and updates the `README.md` accordingly.

### CODE REVIEW

**Comment by mklaber** [comment]
Currently you can add this package using:

```shell
bower install git@github.com:ethicalelectric/SalesforceCanvasJavascriptSDK.git --save
```

After this PR is accepted, someone should [register](http://bower.io/docs/creating-packages/#register) the bower package using:

```
bower register salesforce-canvas-js-sdk git://github.com:forcedotcom/SalesforceCanvasJavascriptSDK.git
```

(I could, but probably best to come from someone at SF)

**Comment by AndyBean** [comment]
+1 for the Bower support request, and I completely agree.

**Comment by jamesward** [comment]
+1

**Comment by vpasquier** [comment]
+1

**Comment by idanblich** [comment]
+1

**Comment by mpsenn** [comment]
Given Bower's deprecation, I don't think I'll merge this. Unless someone still requests this. I am working on updating salesforce-canvas-javascript-sdk on npm, and making this easier to import as a module.

https://www.npmjs.com/package/salesforce-canvas-javascript-sdk

**Comment by jamesward** [comment]
Yeah, NPM would be great.  There is a Salesforce org that you should be able to put this in.

**Comment by mpsenn** [comment]
Published to the @salesforce org on npm.
https://www.npmjs.com/package/@salesforce/canvas-js-sdk

**Comment by jamesward** [comment]
Awesome!  Thank you.

**Pull request closed without merging**
